-- MySQL Script generated by MySQL Workbench
-- Mon Apr 26 15:46:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema parkit_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `parkit_db` ;

-- -----------------------------------------------------
-- Schema parkit_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parkit_db` DEFAULT CHARACTER SET utf8 ;
USE `parkit_db` ;

-- -----------------------------------------------------
-- Table `parkit_db`.`Parking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parkit_db`.`Parking` ;

CREATE TABLE IF NOT EXISTS `parkit_db`.`Parking` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `capacity` INT NOT NULL,
  `priceperhour` FLOAT NULL,
  `priceperday` FLOAT NULL,
  `pricepermonth` FLOAT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parkit_db`.`Sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parkit_db`.`Sensor` ;

CREATE TABLE IF NOT EXISTS `parkit_db`.`Sensor` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Parking_id` INT NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`id`, `Parking_id`),
  INDEX `fk_Sensor_Parking_idx` (`Parking_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sensor_Parking`
    FOREIGN KEY (`Parking_id`)
    REFERENCES `parkit_db`.`Parking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
